variables:
  GIT_STRATEGY: fetch

bundlejs:
  image: node:7.0.0
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install --silent
    - npm build
    - ls -R assets
  artifacts:
    paths:
      - assets/js


test:
  image: ruby:2.3
  stage: test
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d test
  dependencies:
    - bundlejs
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  image: ruby:2.3
  stage: deploy
  script:
  - ls -R
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d public
  dependencies:
    - bundlejs
  artifacts:
    paths:
    - public
  only:
  - master
