
cache:
  paths:
    - node_modules/

bundlejs:
  image: node:7.0.0
  stage: build
  script:
    - npm install --silent
    - npm build
  artifacts:
    paths:
      - assets/js


test:
  image: ruby:2.3
  stage: test
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  image: ruby:2.3
  stage: deploy
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
