# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll

bundlejs:
  image: node:7.0.0
  stage: build
  script:
    - npm install --silent
    - npm build

test:
  image: ruby:2.3
  stage: test
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  image: ruby:2.3
  stage: deploy
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - webpack
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
