# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/jekyll
image: ruby:2.3

bundlejs:
  stage: build
  script:
    - webpack -p --config ./webpack.production.config.js

test:
  stage: test
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
  - webpack
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
