# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: The Political Revolution
title-normal: Progressives for the People
email: info@thepoliticalrev.org
description: "We can change the future of America, but we need your help."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepoliticalrev.org" # the base hostname & protocol for your site
author:
  twitter: "@OurPoliticalRev"
street_address:
city:
state:
zip_code:
country:
phone:

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# Social settings
medium_url: https://medium.com/@OurPoliticalRev
facebook_url: https://www.facebook.com/ThePoliticalRev/
github_url:
gitlab_url: https://gitlab.com/groups/political-revolution
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://polrevvols.herokuapp.com/
twitter_url: https://twitter.com/OurPoliticalRev
subreddit_url: https://reddit.com/r/Political_Revolution

# Build settings
markdown: kramdown
sass:
  style: compressed
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
exclude:
  - webpack.config.js
  - webpack.production.config.js
  - package.json
  - README.md
  - id_gitlab.txt
  - deploy.sh
  - clear-server.sh
  - node_modules/

# Prose editor config
prose:
  # rooturl: "_posts"
  ignore:
    - _sass
    - _includes
    - _layouts
    - .travis.yml
    - .babelrc
    - .gitignore
    - .gitlab-ci.yml
    - _github-config.yml
    - package.json
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - browserconfig.xml
    - ci-compile.sh
    - ci-deploy.sh
    - clear-server.sh
    - deploy.sh
    - deploy_key.enc
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico
    - favicons.zip
    - id_rsa.enc
    - manifest.json
    - mstile-150x150.png
    - safari-pinned-tab.svg
    - webpack.config.js
    - webpack.production.config.js

  siteurl: "https://politicalrev.github.io/thepoliticalrev.org/"
  media: "assets/images/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          type: "text"
      - name: "author-googleplus"
        field:
          element: "text"
          label: "Author Google+ Accont Link"
          help: "Used for google author attribution"
          type: "text"
          placeholder: "https://plus.google.com/<your-username>"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          help: "(optional) Short description or excerpt to show in post index."
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Post Image"
          help: "Add an image from the \"Insert Image\" button above the editor. Then, copy and paste the image link (without the \"{{base.url}}\" part) to this textbox. Finally, make sure to remove the image link from the post body."
          type: "text"
          placeholder: "/assets/images/posts/<filename>"

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      title: ""
      banner: "no"
      layout: default
  -
    scope:
      path: "_posts"
    values:
      medium: "yes"

# Plugin: jekyll-seo-tag
twitter:
  username: "@OurPoliticalRev"
  plain_username: "OurPoliticalRev"
# Add one or more of the following
facebook:
  app_id: 206987373045662
  publisher:
  admins:
logo: "assets/images/button.png"
google_site_verification:
