# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: The Political Revolution
title-normal: Progressives for the People
email: info@thepoliticalrev.org
description: "We are a volunteer-run organization working to get candidates inspired by the Bernie Sanders platform into office. Sign up below to join the Revolution:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://political-revolution.gitlab.io" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# Social settings
medium_url: https://medium.com/@OurPoliticalRev
facebook_url: https://www.facebook.com/ThePoliticalRev/
github_url:
gitlab_url: https://gitlab.com/groups/political-revolution
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://polrevvols.herokuapp.com/
twitter_url: https://twitter.com/OurPoliticalRev

# Build settings
markdown: kramdown
sass:
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      title: ""
      banner: "no"

# Plugin: jekyll-seo-tag
twitter:
  username:
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
